# GitHub Sponsors button — displays at the top of the repo
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
github: chartmann1590
buy_me_a_coffee: charleshartmann
custom: ["https://buymeacoffee.com/charleshartmann"]
